version: "3"

services:
  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    restart: on-failure
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "${SERVER2_HOST_DNS}:2181"
      KAFKA_LISTENERS: INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL_SASL_PLAINTEXT://${SERVER3_HOST_DNS}:9092,SASL_PLAINTEXT://${SERVER3_HOST_DNS}:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SASL_PLAINTEXT
      KAFKA_AUTHENTICATION: KERBEROS
      KAFKA_KERBEROS_PUBLIC_URL: "${SERVER1_HOST_DNS}"
      KAFKA_KERBEROS_REALM: "${KERBEROS_REALM}"
      KAFKA_KERBEROS_API_URL: "http://${SERVER1_HOST_DNS}:6000/get-keytab"
      KAFKA_KERBEROS_API_KAFKA_USERNAME: "kafka/${SERVER3_HOST_DNS}"
      KAFKA_KERBEROS_API_KAFKA_PASSWORD: "${KAFKA_PASSWORD}"
      KAFKA_KERBEROS_API_ZOOKEEPER_USERNAME: "zookeeper/${SERVER2_HOST_DNS}"
      KAFKA_KERBEROS_API_ZOOKEEPER_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_ACL_ENABLE: "true"
      KAFKA_ACL_SUPER_USERS: User:kafka;User:admin;User:dashboardserver;User:dashboardinterface
      KAFKA_ZOOKEEPER_SET_ACL: "true"
    volumes:
      - ./kafka-data:/data/kafka
      - ./kafka-logs:/opt/kafka/logs
