version: "3"

services:
  kerberos-db:
    image: postgres
    container_name: kerberos-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${KERBEROS_DB_USER_NAME}"
      POSTGRES_PASSWORD: "${KERBEROS_DB_USER_PASSWORD}"
      POSTGRES_DB: kerberos_db

  kerberos:
    image: cfei/kerberos
    container_name: kerberos
    network_mode: "host"
    environment:
      KERBEROS_API_KEY: "${KERBEROS_API_KEY}"
      KERBEROS_HOST_DNS: "${HOST_DNS}"
      KERBEROS_REALM: "${KERBEROS_REALM}"
      KERBEROS_API_PORT: 6000
      KERBEROS_POSTGRES_CONNECTION_STRING: "Host=${HOST_DNS};Port=5432;Database=kerberos_db;Username=${KERBEROS_DB_USER_NAME};Password=${KERBEROS_DB_USER_PASSWORD};"
      KERBEROS_INIT_USERS: "Username=zookeeper;Password=${ZOOKEEPER_PASSWORD};Host=${HOST_DNS},Username=kafka;Password=${KAFKA_PASSWORD};Host=${HOST_DNS},Username=admin;Password=${ADMIN_PASSWORD}"
    depends_on:
      - kerberos-db

  zookeeper:
    image: cfei/zookeeper:2.0.0-beta
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_AUTHENTICATION: KERBEROS
      ZOO_KERBEROS_PUBLIC_URL: "${HOST_DNS}"
      ZOO_KERBEROS_API_URL: "http://${HOST_DNS}:6000/get-keytab"
      ZOO_KERBEROS_API_USERNAME: "zookeeper/${HOST_DNS}"
      ZOO_KERBEROS_API_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      ZOO_KERBEROS_REALM: "${KERBEROS_REALM}"
      ZOO_REMOVE_HOST_AND_REALM: "true"
    depends_on:
      - kerberos

  acl-manager:
    image: cfei/acl-security-manager
    container_name: acl-manager
    ports:
      - 9000:9000
    environment:
      AUTHORIZER_ZOOKEEPER_CONNECT: "${HOST_DNS}:2181"
      ACL_API_PORT: 9000
      ACL_API_KEY: "${ACL_MANAGER_API_KEY}"
      ACL_KERBEROS_PUBLIC_URL: "${HOST_DNS}"
      ACL_KERBEROS_API_URL: "http://${HOST_DNS}:6000/get-keytab"
      ACL_KERBEROS_API_ZOOKEEPER_USERNAME: "zookeeper/${HOST_DNS}"
      ACL_KERBEROS_API_ZOOKEEPER_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      ACL_KERBEROS_REALM: "${KERBEROS_REALM}"
    depends_on:
      - zookeeper
      - kerberos

  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "${HOST_DNS}:2181"
      KAFKA_LISTENERS: INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL_SASL_PLAINTEXT://${HOST_DNS}:9092,SASL_PLAINTEXT://${HOST_DNS}:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SASL_PLAINTEXT
      KAFKA_AUTHENTICATION: KERBEROS
      KAFKA_KERBEROS_PUBLIC_URL: "${HOST_DNS}"
      KAFKA_KERBEROS_REALM: "${KERBEROS_REALM}"
      KAFKA_KERBEROS_API_URL: "http://${HOST_DNS}:6000/get-keytab"
      KAFKA_KERBEROS_API_KAFKA_USERNAME: "kafka/${HOST_DNS}"
      KAFKA_KERBEROS_API_KAFKA_PASSWORD: "${KAFKA_PASSWORD}"
      KAFKA_KERBEROS_API_ZOOKEEPER_USERNAME: "zookeeper/${HOST_DNS}"
      KAFKA_KERBEROS_API_ZOOKEEPER_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_ACL_ENABLE: "true"
      KAFKA_ACL_SUPER_USERS: User:kafka;User:admin
      KAFKA_ZOOKEEPER_SET_ACL: "true"
    depends_on:
      - kerberos
      - zookeeper

  interface-db:
    image: postgres
    container_name: interface-db
    environment:
      POSTGRES_USER: "${DASHBOARD_DB_USER_NAME}"
      POSTGRES_PASSWORD: "${DASHBOARD_DB_USER_PASSWORD}"
      POSTGRES_DB: interface_db

  interface:
    image: cfei/dashboard-interface
    container_name: interface
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      DASHBOARDI_UI_PORT: 3000
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-db;Port=5432;Database=interface_db;Username=${DASHBOARD_DB_USER_NAME};Password=${DASHBOARD_DB_USER_PASSWORD}"
      DASHBOARDI_API_KEY: "${DASHBOARD_API_KEY}"
      DASHBOARDI_JWT_KEY: "${DASHBOARD_JWT_KEY}"
      DASHBOARDI_INIT_USER_EMAIL: "${DASHBOARD_USER_EMAIL}"
      DASHBAORDI_INIT_PASSWORD: "${DASHBOARD_USER_PASSWORD}"
      DASHBOARDI_API_DNS: "https://${HOST_DNS}:5000"
      DASHBOARDI_KAFKA_URL: "${HOST_DNS}:9093"
    depends_on:
      - interface-db
      - kerberos

  dashboard-server:
    image: cfei/dashboard-server
    container_name: dashboard-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVER_NAME: SingleServer
      KAFKA_URL: "${HOST_DNS}:9093"
    depends_on:
      - interface
      - kerberos
