version: "3"

services:
  zoo1:
    image: cfei/zookeeper:1.1.0
    container_name: zoo1
    restart: on-failure
    ports:
      - 2181:2181
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888,server.2=zoo2:2888:3888,server.3=zoo3:2888:3888
    # volumes:
    #   - ./containervolumes/zookeeper1-data:/data/zookeeper

  zoo2:
    image: cfei/zookeeper:1.1.0
    container_name: zoo2
    restart: on-failure
    ports:
      - 2182:2181
    environment:
      ZOO_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888,server.2=0.0.0.0:2888:3888,server.3=zoo3:2888:3888
    # volumes:
    #   - ./containervolumes/zookeeper2-data:/data/zookeeper

  zoo3:
    image: cfei/zookeeper:1.1.0
    container_name: zoo3
    restart: on-failure
    ports:
      - 2183:2181
    environment:
      ZOO_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888,server.2=zoo2:2888:3888,server.3=0.0.0.0:2888:3888
    # volumes:
    #   - ./containervolumes/zookeeper3-data:/data/zookeeper

  kafka1:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka1
    restart: on-failure
    ports:
      - 9091:9091
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181/kafka,zoo2:2181/kafka,zoo3:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092,DOCKER_LISTENER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:9091,EXTERNAL://${HOST_DNS}:9092,DOCKER_LISTENER://kafka1:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_HEALTHCHECK_PORT: 9091
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    # volumes:
    #   - ./containervolumes/kafka-data1:/data/kafka

  kafka2:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka2
    restart: on-failure
    ports:
      - 9093:9093
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181/kafka,zoo2:2181/kafka,zoo3:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094,DOCKER_LISTENER://0.0.0.0:19094
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:9093,EXTERNAL://${HOST_DNS}:9094,DOCKER_LISTENER://kafka2:19094"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_HEALTHCHECK_PORT: 9093
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    # volumes:
    #   - ./containervolumes/kafka-data2:/data/kafka

  kafka3:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka3
    restart: on-failure
    ports:
      - 9095:9095
      - 9096:9096
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181/kafka,zoo2:2181/kafka,zoo3:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9095,EXTERNAL://0.0.0.0:9096,DOCKER_LISTENER://0.0.0.0:19096
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:9095,EXTERNAL://${HOST_DNS}:9096,DOCKER_LISTENER://kafka3:19096"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_HEALTHCHECK_PORT: 9095
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    # volumes:
    #   - ./containervolumes/kafka-data3:/data/kafka

  interface-db:
    image: postgres
    container_name: interface-db
    restart: on-failure
    environment:
      POSTGRES_USER: "${DASHBOARD_DB_USER_NAME}"
      POSTGRES_PASSWORD: "${DASHBOARD_DB_USER_PASSWORD}"
      POSTGRES_DB: interface_db
    # volumes:
    #   - ./containervolumes/interface-postgres-data:/var/lib/postgresql/data

  interface:
    image: cfei/dashboard-interface
    container_name: interface
    restart: on-failure
    ports:
      - 80:80
      - 5000:5000
    environment:
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-db;Port=5432;Database=interface_db;Username=${DASHBOARD_DB_USER_NAME};Password=${DASHBOARD_DB_USER_PASSWORD}"
      DASHBOARDI_HOST_DNS: "http://${HOST_DNS}"
      DASHBOARDI_API_KEY: "${DASHBOARD_API_KEY}"
      DASHBOARDI_JWT_KEY: "${DASHBOARD_JWT_KEY}"
      DASHBOARDI_INIT_USER_EMAIL: "${DASHBOARD_USER_EMAIL}"
      DASHBAORDI_INIT_PASSWORD: "${DASHBOARD_USER_PASSWORD}"
      DASHBOARDI_JWT_ISSUER: "https://${HOST_DNS}:5000"
      DASHBOARDI_KAFKA_URL: kafkaf1:19092,kafka2:19094,kafka3:19096
    depends_on:
      - interface-db
      - kafka1
      - kafka2
      - kafka3

  dashboard-server:
    image: cfei/dashboard-server
    container_name: dashboard-server
    restart: on-failure
    environment:
      DASHBOARDS_SERVER_NAME: SingleServer
      DASHBOARDS_KAFKA_URL: kafkaf1:19092,kafka2:19094,kafka3:19096
    depends_on:
      - interface
      - kafka1
      - kafka2
      - kafka3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Wesley
  wesley-mysql:
    image: mysql
    container_name: wesley-mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 532c5b0a-2cd9-4eed-ad10-6dcdea6e732b
      MYSQL_USER: archiver
      MYSQL_PASSWORD: c0d9f4f4-f978-4ff3-98a7-8a30a182bbd9
      MYSQL_DATABASE: metadata
    # volumes:
    #   - ./containervolumes/wesley-mysql:/var/lib/mysql

  cassandra1:
    image: cassandra
    container_name: cassandra1
    restart: on-failure
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
    # volumes:
    #   - ./containervolumes/cassandra1/data:/opt/cassandra/data

  cassandra2:
    image: cassandra
    container_name: cassandra2
    restart: on-failure
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
    # volumes:
    #   - ./containervolumes/cassandra2/data:/opt/cassandra/data

  wesley:
    image: cfei/wesley:0.3
    container_name: wesley
    restart: on-failure
    environment:
      KAFKA_SUBDB: /var/log/wesley/kafka_subscriptions.txt
      KAFKA_BROKERS: kafkaf1:19092,kafka2:19094,kafka3:19096
      KAFKA_GROUP: uniten_archiver
      KAFKA_PREFIX: uniten_archiver
      MYSQL_HOST: wesley-mysql
      MYSQL_PORT: 3306
      MYSQL_USER: archiver
      MYSQL_PASSWORD: "${WESLEY_MYSQL_PASSWORD}"
      MYSQL_DATABASE: metadata
      CASSANDRA_HOSTS: cassandra1,cassandra2
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: data
      CASSANDRA_TABLE_PREFIX: prefix_is_currently_hardcoded
    volumes:
      - ./containervolumes/wesley-logs:/var/log/wesley
    depends_on:
      - wesley-mysql
      - cassandra1
      - cassandra2
      - kafka1
      - kafka2
      - kafka3