version: "3"

services:    
  kerberos-db:
    image: postgres
    container_name: kerberos-db
    environment:
      POSTGRES_USER: kerberos
      POSTGRES_PASSWORD: Kerberos_Password1
      POSTGRES_DB: kerberos_db
    networks:
      - back

  kerberos:
    image: cfei/docker-kerberos
    container_name: kerberos
    ports:
      - 6000:6000
    environment:
      KERBEROS_ADMIN_PW: "${KERBEROS_API_KEY}"
      KERBEROS_HOST_DNS: "${HOST_DNS}"
      KERBEROS_REALM: "${KERBEROS_REALM}"
      KERBEROS_API_PORT: 6000
      KERBEROS_POSTGRES_CONNECTION_STRING: "Host=kerberos-db;Port=5432;Database=kerberos_db;Username=kerberos;Password=Kerberos_Password1;"
    depends_on:
      - kerberos-db
    networks:
      - front
      - back
  
  zookeeper:
    image: cfei/zookeeper:2.0.0-beta
    container_name: zookeeper
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_AUTHENTICATION: KERBEROS
      ZOO_KERBEROS_PUBLIC_URL: "${HOST_DNS}"
      ZOO_KERBEROS_API_URL: "http://kerberos:3000/get-keytab"
      ZOO_KERBEROS_API_USERNAME: "zookeeper/${HOST_DNS}"
      ZOO_KERBEROS_API_PASSWORD: zookeeperPassword
      ZOO_KERBEROS_REALM: "${KERBEROS_REALM}"
      ZOO_REMOVE_HOST_AND_REALM: "true"
    depends_on: 
      - kerberos
    networks:
      - back

  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    env_file: 
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL_SASL_PLAINTEXT://${HOST_DNS}:9092,SASL_PLAINTEXT://${HOST_DNS}:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SASL_PLAINTEXT
      KAFKA_AUTHENTICATION: KERBEROS
      KAFKA_KERBEROS_PUBLIC_URL: "${HOST_DNS}"
      KAFKA_KERBEROS_REALM: "${KERBEROS_REALM}"
      KAFKA_KERBEROS_API_URL: http://kerberos:3000/get-keytab
      KAFKA_KERBEROS_API_KAFKA_USERNAME: "kafka/${HOST_DNS}"
      KAFKA_KERBEROS_API_KAFKA_PASSWORD: kafkaPasswordTester
      KAFKA_KERBEROS_API_ZOOKEEPER_USERNAME: "zookeeper/${HOST_DNS}"
      KAFKA_KERBEROS_API_ZOOKEEPER_PASSWORD: zookeeperPasswordTester
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_ACL_ENABLE: "true"
      KAFKA_ACL_SUPER_USERS: User:kafka;User:admin
      KAFKA_ZOOKEEPER_SET_ACL: "true"
    depends_on: 
      - kerberos
      - zookeeper
    networks:
      - front
      - back

  dashboard-server:
    image: omvk97/docker-dashboard-server
    container_name: dashboard-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVER_NAME: SingleServer
    networks:
      - back

  interface-db:
    image: postgres
    container_name: interface-db
    environment:
      POSTGRES_USER: interface
      POSTGRES_PASSWORD: Interface_database_password1
      POSTGRES_DB: interface_db
    networks:
      - back

  interface:
    image: omvk97/docker-dashboard-interface
    container_name: interface
    ports:
      - 3001:3001
      - 5000:5000
    environment:
      DASHBOARDI_UI_PORT: 3001
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-database;Port=5432;Database=interface_db;Username=interface;Password=Interface_database_password1"
      DASHBOARDI_API_KEY: "${DASHBOARD_API_KEY}"
      DASHBOARDI_JWT_KEY: "${DASHBOARD_JWT_KEY}"
      DASHBOARDI_INIT_USER_EMAIL: "${DASHBOARD_USER_EMAIL}"
      DASHBAORDI_INIT_PASSWORD: "${DASHBOARD_USER_PASSWORD}"
    depends_on:
      - interface-db
      - dashboard-server
    networks:
      - back
      - front

networks:
  front:
    driver: bridge
  back:
    driver: bridge
