@startuml
hide footbox
skinparam sequenceMessageAlign center

Title "Refetch Overview Data"


actor "User" as user

participant "Dashboard Interface (UI)" as ui
participant "Dashboard Interface (SocketServer)" as socketserver
participant "Kafka" as kafka
participant "Dashboard Server" as dserver

user -> ui : Refetch Overview Data
activate ui
ui -> socketserver : RefetchOverviewData(topic)
activate socketserver
activate kafka
socketserver -> kafka : Refetch request serialised
kafka -> dserver : Refetch request serialised
deactivate kafka
activate dserver
dserver -> dserver : DeserializeObject(Refetch request serialised)

alt Refetch Request follows corrects format
    dserver -> dserver : RefetechOverviewData
    dserver -> kafka : Send Overview Data to overview topic
    dserver -> kafka : Succesful message to response topic
    kafka -> socketserver : Send Overview Data to overview topic
    kafka -> socketserver : Succesful message to response topic
    socketserver -> ui : Updated overview data
    socketserver -> ui : Succesful message
    ui -> user : Update overview data
    ui -> user : Graphical succesful message
else Refetch Request incorrect format
    dserver -> kafka : Error message to response topic
    activate kafka
    deactivate dserver
    kafka -> socketserver : Error message to response topic
    deactivate kafka
    socketserver -> ui : Error message
    ui -> user : Graphical error message
    deactivate ui
    deactivate socketserver
end
@enduml