@startuml
hide footbox
skinparam sequenceMessageAlign center

Title "Create Kerberos User"

actor "Kerberos Admin" as kadmin
actor "Security Admin" as sadmin

participant "Kerberos" as kerberos
database "Kerberos Database" as kdata

participant "Security Manager" as smanager
participant "Zoo" as zoo

kadmin -> kerberos : Create Keytab (apikey, username, password)

kerberos -> kerberos : Create User(username, password)
note left
    Kerberos Admin can create the keytab either
    with a POST request 
    or with the use of Dashboard-Interface
end note
kerberos -> kerberos : Create Keytab
kerberos -> kdata : Store Keytab

sadmin -> smanager : Create super user(apikey, username)
smanager -> zoo : Store new super user privileges
note left
    Security Admin can create the super user either
    with a POST request 
    or with the use of Dashboard-Interface
end note

@enduml