@startuml
hide footbox
skinparam sequenceMessageAlign center

Title "Kerberos login"


actor "External Service" as es

participant "Kerberos" as kerberos

participant "Kafka" as kafka
participant "Zoo" as zoo

es -> kerberos : FetchKeytab(username, password)
note left
    This diagram takes place after
    CreateKerberosUser. 
    External Service is an example service
    wanting to use kafka
end note
return Keytab

es -> kafka : Communicate(keytab)
kafka -> zoo : Check user privileges

@enduml