@startuml
hide footbox
skinparam sequenceMessageAlign center

Title "Kerberos login"

actor "External Service" as es

participant "Kerberos Web Server" as kerberosws
database "Kerberos Database" as kdata

participant "Kafka" as kafka

participant "Zookeeper" as zoo

es -> kerberosws : FetchKeytab(username, password)
activate kerberosws
note left
    This diagram takes place after
    ExternalServiceAccessExample. 
    External Service is an example service
    wanting to use kafka
end note

kerberosws -> kdata : FetchKeytab()
activate kdata
kdata -> kerberosws: Keytab
deactivate kdata

kerberosws -> es: Keytab
deactivate kerberosws

es -> kafka : Authenticate using Keytab
note right
    This is an abstraction of the authentication
    process between kafka, zookeeper and kerberos.
end note
kafka -> zoo : Check user privileges

@enduml