version: "3"

services:
  interface-db:
    image: postgres
    container_name: interface-db
    restart: always
    environment:
      POSTGRES_USER: "${DASHBOARD_DB_USER_NAME}"
      POSTGRES_PASSWORD: "${DASHBOARD_DB_USER_PASSWORD}"
      POSTGRES_DB: interface_db

  interface:
    image: cfei/dashboard-interface
    container_name: interface
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      DASHBOARDI_UI_PORT: 3000
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-db;Port=5432;Database=interface_db;Username=${DASHBOARD_DB_USER_NAME};Password=${DASHBOARD_DB_USER_PASSWORD}"
      DASHBOARDI_API_KEY: "${DASHBOARD_API_KEY}"
      DASHBOARDI_JWT_KEY: "${DASHBOARD_JWT_KEY}"
      DASHBOARDI_INIT_USER_EMAIL: "${DASHBOARD_USER_EMAIL}"
      DASHBAORDI_INIT_PASSWORD: "${DASHBOARD_USER_PASSWORD}"
      DASHBOARDI_API_DNS: "https://${SERVER1_HOST_DNS}:5000"
      DASHBOARDI_KAFKA_URL: 
    depends_on: 
      - interface-db