version: "3"

services:
  zookeeper:
    image: cfei/zookeeper:2.0.0-beta
    container_name: zookeeper
    restart: on-failure
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_AUTHENTICATION: KERBEROS
      ZOO_KERBEROS_PUBLIC_URL: "${SERVER1_HOST_DNS}"
      ZOO_KERBEROS_API_URL: "http://${SERVER1_HOST_DNS}:6000/get-keytab"
      ZOO_KERBEROS_API_USERNAME: "zookeeper/${SERVER2_HOST_DNS}"
      ZOO_KERBEROS_API_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      ZOO_KERBEROS_REALM: "${KERBEROS_REALM}"
      ZOO_REMOVE_HOST_AND_REALM: "true"
    volumes:
      - ./zookeeper-data:/data/zookeeper
      - ./zookeeper-logs:/datalogs/zookeeper

  acl-manager:
    image: cfei/acl-security-manager
    container_name: acl-manager
    restart: on-failure
    ports:
      - 9000:9000
    environment:
      AUTHORIZER_ZOOKEEPER_CONNECT: "${SERVER2_HOST_DNS}:2181/kafka"
      ACL_API_PORT: 9000
      ACL_API_KEY: "${ACL_MANAGER_API_KEY}"
      ACL_KERBEROS_PUBLIC_URL: "${SERVER1_HOST_DNS}"
      ACL_KERBEROS_API_URL: "http://${SERVER1_HOST_DNS}:6000/get-keytab"
      ACL_KERBEROS_API_ZOOKEEPER_USERNAME: "zookeeper/${SERVER2_HOST_DNS}"
      ACL_KERBEROS_API_ZOOKEEPER_PASSWORD: "${ZOOKEEPER_PASSWORD}"
      ACL_KERBEROS_REALM: "${KERBEROS_REALM}"
    depends_on:
      - zookeeper
    volumes:
      - ./aclmanager-conf:/conf
